### ISSUE TITLE
What is the proper way to update time on a task?

### ISSUE THREAD

**Issue by stephencross** [kostajh/taskwarrior-time-tracking-hook#24]
Is it possible to update time on a task without Start/Stopping it? 

-S

**Comment by PorcelainMouse** [comment]
Great tool!

Yes, this is a great question; I'm sorry you haven't had any replies, yet.  AFAIK, the only way to do this is by manually changing the task on disk, in the .data file.  And I don't think that is safe to do, especially when you have sync configured.  I have done it on one completed task, which seemed to not break things.

Now, you can do the logical thing:
`task mod totalactivetime=60seconds # wrong?`
but this doesn't work! The value specified gets translated by taskwarrior into a duration type, which is like PTXXHXXMXXS or something.  This seems helpful, but, in fact, this is *not* how taskwarrior records the time, which makes other tools, like taskTime.py break.

So, I would also like to know how to fix this.  Is there a way to prevent task from interpreting the duration spec, perhaps temporarily?

**Comment by PorcelainMouse** [comment]
Hmm, wait.  I just tried my own solution again, and it seems to work!

**Comment by PorcelainMouse** [comment]
Okay, I think I figured it out.  The documentation says to use type 'duration' for the type of UDA property 'uda.totalactivetime.type'.  But, this causes taskw to use convert durations to ISO type, which the time tracking hook cannot use; it crashed at at int() cast.

By setting the type of this property to 'string', instead of duration, I was able to set the value manually, in the "standard" way with task command, without having it automatically converted to ISO format.  This allows you to manipulate the totalactive time value for task without crashing this hook.

**Comment by brp-optics** [comment]
@PorcelainMouse I have been able to manually force changes to the duration with the following shell code:

```
$task 1 mod tot:1000seconds
```

My version of taskwarrior translates this to a duration automatically, so it is translated to readable approximations in `info` reports. The hook reads the durations properly and adds further time later. (Note that out of the box durations like "minutes" are not recognized by the hook. I have my own parser for this, but it isn't pretty enough to share.)

Perhaps you need to update time tracking hook, or your version of taskwarrior is not up to date?

**Comment by PorcelainMouse** [comment]
Hmm, did you try using my syntax?  I think that would tell you if that is the problem or not.

I asked pip to upgrade taskwarrior-time-tracking-hook and it says I have 0.1.4  and is up-to-date.  Is that not correct?

**Comment by PorcelainMouse** [comment]
I tried putting it back to to type 'duration' and got the same result.

$ task 176 start
Configuration override rc.verbose:off
Starting task 78bfb322 '<redacted>'.
Started 1 task.
$ task 176 stop
Traceback (most recent call last):
  File "/home/<readacted>/.task/hooks/on-modify.timetracking", line 8, in <module>
    sys.exit(cmdline())
  File "/home/<readacted>/.local/lib/python3.8/site-packages/taskwarrior_time_tracking_hook/__init__.py", line 68, in cmdline
    sys.stdout.write(main())
  File "/home/<readacted>/.local/lib/python3.8/site-packages/taskwarrior_time_tracking_hook/__init__.py", line 49, in main
    + datetime.timedelta(seconds=int(
ValueError: invalid literal for int() with base 10: 'PT1H21M55S'
Hook Error: Expected feedback from a failing hook script.

If totalactivetime contains a value of type duration, the hook cannot update it.

**Comment by brp-optics** [comment]
So, when I execute your command, I end up renaming the task instead of setting the total active time:

```shell
$ task add "test task"
Created task 989.

$ task 989 mod totalactivetime=60seconds
Modifying task 989 'totalactivetime=60seconds'.
Modified 1 task.

$ task 989
Name              Value
ID                989
Description       totalactivetime=60seconds
Status            Pending
Entered           <...>
Last modified     <...>
Virtual tags      ANNOTATED PENDING READY UNBLOCKED
UUID              f77b03e4-<...>
Urgency            0.9
```

That said, it looks like you do have an interesting bug...

**Comment by brp-optics** [comment]
@PorcelainMouse I was able to reproduce your bug by specifying the `totalactivetime` in ISO notation:

```shell
$ task add "test task" totalactivetime:PT1H21M55S
Created task 989.

$ task 989 start
...

$ task 989 stop
Traceback (most recent call last):
  File "/home/<...>/.task/hooks/on-modify.timetracking", line 11, in <module>
    load_entry_point('taskwarrior-time-tracking-hook==0.1.4', 'console_scripts', 'taskwarrior_time_tracking_hook')()
  File "/usr/lib/python3.7/site-packages/taskwarrior_time_tracking_hook/__init__.py", line 68, in cmdline
    sys.stdout.write(main())
  File "/usr/lib/python3.7/site-packages/taskwarrior_time_tracking_hook/__init__.py", line 50, in main
    str(modified[UDA_KEY]).rstrip("seconds")
ValueError: invalid literal for int() with base 10: 'PT1H21M55S'
Hook Error: Expected feedback from a failing hook script.
```

It seems that for you Taskwarrior may be converting `XXseconds` into ISO durations (`P...T...`), which chokes the parser of version 0.1.4 of `taskwarrior-time-tracking-hook`, whereas my Taskwarrior client (2.4.4 on Cygwin) is content to leave `totalactivetime` as `XX seconds` in `.task/backlog.data`, despite `totalactivetime` being specified as a duration.

From here it seems there are four possible ways forward (besides changing your taskwarrior client.) 
(0) Delete the task and try again, specifying time in seconds, instead of using the ISO notation for duration. Does this work?

(1) Specify the UDA to be a number instead of a duration.

(2) Edit the task databases directly to store "XX seconds"... obviously not practical.

(3) Replace the pip version of the hook with the current github code manually, since the current github code parses ISO notation properly. When I moved "__init__.py" (it looks like for you it is (`init.py`) to `__init__.py.old` and created a new `__init__.py` in the same directory with the current contents of the file `__init__.py` from this repository, I got the following result:

```shell
$ task 989 stop
Stopping task f77b03e4-<...> 'test task'.
Stopped 1 task.
Total Time Tracked: 0:11:48.531476 (0:11:48.531476 in this instance)
```

**Comment by PorcelainMouse** [comment]
> It seems that for you Taskwarrior may be converting `XXseconds` into ISO durations (`P...T...`), which chokes the parser of version 0.1.4 of `taskwarrior-time-tracking-hook`, whereas my Taskwarrior client (2.4.4 on Cygwin) is content to leave `totalactivetime` as `XX seconds` in `.task/backlog.data`, despite `totalactivetime` being specified as a duration.

Yes, that seems pretty clear.  But, it is your client that is out of date; I have 2.5.1.  I don't plan to use a local build, either.  If it is a bug with the client, I am happy to report to my distro, though.  Just help me convince them to fix it.

> From here it seems there are four possible ways forward (besides changing your taskwarrior client.)
> (0) Delete the task and try again, specifying time in seconds, instead of using the ISO notation for duration. Does this work?

Yes and no.  No, with the uda set to type duration, it converts it or fails.

Yes, with the uda set to type string, things run as before.  For me, totalactivetime was never recorded as a duration, and so setting the type to string preserves the original behavior.  That's what I have been doing since this problem started, which was after distro upgrade.  Something seems to have changed, probably with my client 2.5.1 from what you are saying, that started enforcing the type of totalactivetime.  I think we agree on all the pieces of this bug.

> 
> (1) Specify the UDA to be a number instead of a duration.

No, that does not work.  I think I tried that first.

> (2) Edit the task databases directly to store "XX seconds"... obviously not 

I already confirmed this works.
 
> (3) Replace the pip version of the hook with the current github code manually, since the current github code parses ISO notation properly. When I moved `__init__.py` (it looks like for you it is (`init.py`) to `__init__.py.old` and created a new `__init__.py` in the same directory with the current contents of the git repository file `__init__.py`, I got the following result:
> 
> ```shell
> $ task 989 stop
> Stopping task f77b03e4-<...> 'test task'.
> Stopped 1 task.
> Total Time Tracked: 0:11:48.531476 (0:11:48.531476 in this instance)
> ```

Hmm, I don't follow that or like it.
- I have __init__.py, like normal python.  Not sure what you mean.
- I prefer not to mess with my python modules, at least not as a workaround.  But, I'm willing to help debug for a fix.
- my __init__py is the same as master/HEAD (eda92752)

**Comment by PorcelainMouse** [comment]
Ah, okay, i see, I didn't format my error output correctly, so it looked like init.py.  Okay, my mistake.

**Comment by brp-optics** [comment]
>     * my __init__py is the same as master/HEAD ([eda9275](https://github.com/kostajh/taskwarrior-time-tracking-hook/commit/eda92752ea25108e2dda7a8fcc6c42a4b541ffb8))

The master/HEAD you linked to does not contain the code that was in your error message:
> `str(modified[UDA_KEY]).rstrip("seconds")`

If nothing else is working for you, I encourage you to update the raw code in `__init__.py` to fix your issue.

**Comment by PorcelainMouse** [comment]
Fair enough, but that only makes the situation more mysterious.

git says that code was removed in 2014.  Should I not be using pip to install this code?

**Comment by coddingtonbear** [comment]
Oh, hrm; I've just now noticed that I'm still the sole owner of this project on pypi.  @kostajh -- if you could let me know what your pypi username is, I'll transfer the pypi project to you so you could release an updated version.

**Comment by kostajh** [comment]
@coddingtonbear it might be time to find a new co-maintainer, I haven't used Taskwarrior (and thus also this hook) in some time (still have lots of <3 for it though!)
